apiVersion: v1
kind: PersistentVolume
metadata:
  name: cfme-pv03
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  nfs: 
    path: /exports/cfme-pv03
    server: 192.168.122.1
  persistentVolumeReclaimPolicy: Retain
