apiVersion: v1
kind: PersistentVolume
metadata:
  name: cfme-pv01
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  nfs: 
    path: /exports/cfme-pv01
    server: 192.168.122.1
  persistentVolumeReclaimPolicy: Retain

